name: Generate Project

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run generate.sh script
        run: ./generate.sh
